package validation

type Action uint8

const (
	ANY Action = iota
	NONE
	GET_NETWORK
	GET_DEVICE
	GET_DEVICE_NOTIFICATION
	GET_DEVICE_COMMAND
	REGISTER_DEVICE
	CREATE_DEVICE_COMMAND
	UPDATE_DEVICE_COMMAND
	CREATE_DEVICE_NOTIFICATION
	GET_CURRENT_USER
	UPDATE_CURRENT_USER
	MANAGE_USER
	MANAGE_CONFIGURATION
	MANAGE_NETWORK
	MANAGE_TOKEN
	MANAGE_PLUGIN
	GET_DEVICE_TYPE
	MANAGE_DEVICE_TYPE
)
